@startuml

hide footbox

participant ":Parser" as Parser
participant ":AddTimetableCommand" as Command
participant ":Data" as Data
participant ":Module" as Module
participant ":Lesson" as Lesson
participant ":Ui" as Ui


[-> Parser : parse("add timetable")
activate Parser

ref over Parser, Command : getCommand

[<-- Parser : AddTimetableCommand
deactivate Parser

[->Command : execute()
activate Command

Command -> Data : find(moduleCode)
activate Data

Data --> Command : module
deactivate Data


Command -> Lesson ** : Lesson(day, startTime, endTime, venue, lessonType)
activate Lesson

Lesson --> Command : lesson
deactivate Lesson

Command -> Module : addLesson(lesson)
activate Module

Module --> Command
deactivate Module

Command -> Ui : printNewTimetable(moduleCode, lesson)
activate Ui

Ui --> Command
deactivate Ui

[<-- Command
deactivate Command

@enduml