@startuml
'https://plantuml.com/sequence-diagram

hide footbox

loop over scanner.hasNext()

[-> Storage: loadAnswer()
activate Storage
Storage -> Answer**
activate Answer
Answer --> Storage
deactivate Answer
[<-- Storage: Answer
deactivate Storage

@enduml