@startuml

hide footbox

participant ":Parser" as Parser
participant ":SetAssignmentGradeCommand" as Command
participant ":Data" as Data
participant ":Module" as Module
participant ":Student" as Student
participant ":Assignment" as Assignment
participant ":Ui" as Ui


[-> Parser : parse("set assignment grade")
activate Parser

ref over Parser, Command : getCommand

[<-- Parser : SetAssignmentGradeCommand
deactivate Parser

[->Command : execute()
activate Command

Command -> Data : find(moduleCode)
activate Data

Data --> Command : module
deactivate Data

Command -> Module : findAssignment(assignmentName)
activate Module

Module --> Command : assignment
deactivate Module

Command -> Student : findStudent(studentName)
activate Student

Student --> Command : student
deactivate Student

Command -> Assignment : setStudentGrade(student, grade)
activate Assignment

Assignment --> Command
deactivate Assignment


Command -> Ui : printSetAssignmentGrade(moduleCode, assignmentName, studentName, grade)
activate Ui

Ui --> Command
deactivate Ui

[<-- Command
deactivate Command

@enduml