@startuml

hide footbox

participant ":Parser" as Parser
participant ":SortAssignmentByDeadlineCommand" as Command
participant ":Data" as Data
participant ":Module" as Module
participant ":Ui" as Ui


[-> Parser : parse("sort assignments by deadline")
activate Parser

ref over Parser, Command : getCommand

[<-- Parser : sortAssignmentsByDeadlineCommand
deactivate Parser

[->Command : execute()
activate Command

Command -> Data : find(moduleCode)
activate Data

Data --> Command : module
deactivate Data

Command -> Module : sortAssignments()
activate Module

Module --> Command
deactivate Module

Command -> Ui : listModuleAssignments(module)
activate Ui

Ui --> Command
deactivate Ui

[<-- Command
deactivate Command

@enduml