@startuml

box command
participant ":SetAssignmentDeadlineCommand" as Calc
end box

box data
participant ":BooleanTemplate" as Bool
participant ":BinaryTree" as BT
participant ":Gate" as Gate
end box

[-> Calc : execute()
activate Calc

Calc -> Bool : calculateOutput(index)
activate Bool

ref over Bool, BT : checkIndex

Bool -> BT: getT(index)
activate BT

BT -> Gate : arrayList.get(index)
activate Gate

Gate --> BT : gate
deactivate Gate

BT --> Bool: gate
deactivate BT

ref over Bool, Gate : setIndex

Bool -> Gate : getOutput()
activate Gate

Gate --> Bool: output
deactivate Gate

Bool --> Calc: output
deactivate Bool

[<-- Calc: output
deactivate Calc
@enduml